### ISSUE TITLE
ROS1 

### ISSUE THREAD

**Issue by modulab** [BytesRobotics/ros2_t260#15]
Hi, is this available for ros1, or is there a way to use your code in ros1? I'm trying to do relocalization by getting the maps from t265. thanks

**Comment by Michael-Equi** [comment]
This will only work for ROS2. If you want to make a port to ROS1 it shouldn't take too long. You could also use a ROS bridge between ROS1 and ROS2.

**Comment by modulab** [comment]
Thanks
