### ISSUE TITLE
ROS2 eloquent support 

### ISSUE THREAD

**Issue by ibraEssam** [BytesRobotics/ros2_t260#16]
Hi, 
I was trying to build the package and test it on ROS2 eloquent but I'm having some issues.
```
 ros2_t260/src/lifecycle_client.cpp:73:13: error: ‘rclcpp::FutureReturnCode’ has not been declared
     rclcpp::FutureReturnCode::SUCCESS)

```

```
ros2_t260/t260.hpp:61:10: fatal error: image_transport/image_transport.hpp: No such file or directory
 #include "image_transport/image_transport.hpp"
```

is there anyway to get it running on eloquent?

**Comment by Michael-Equi** [comment]
Hi @HemaZ, currently this repo does not support eloquent. I recommend using https://github.com/IntelRealSense/realsense-ros/tree/eloquent

**Comment by ibraEssam** [comment]
> Hi @HemaZ, currently this repo does not support eloquent. I recommend using https://github.com/IntelRealSense/realsense-ros/tree/eloquent

Great thanks for your reply
